/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.0.0
    2025 12 29 00:07:15
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module addr38 (data_a_re_i, data_b_re_i, result_re_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  [37:0]  data_a_re_i;
    input  [37:0]  data_b_re_i;
    output  [37:0]  result_re_o;
endmodule