/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.6.1
    2026 01 08 09:30:07
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module gpll (rstn_i, clki_i, lock_o, clkop_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rstn_i;
    input  clki_i;
    output  lock_o;
    output  clkop_o;
endmodule