/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.5.0
    2026 01 08 15:16:43
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sin_lut_ddy (rd_clk_i, rst_i, rd_en_i, rd_clk_en_i, rd_addr_i,
    rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rst_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [9:0]  rd_addr_i;
    output  [35:0]  rd_data_o;
endmodule